### ISSUE TITLE
Strange behaviour on Moto G 2014 Android 6.0

### ISSUE THREAD

**Issue by m1cha1** [theScrabi/NewPipe#225]
I have 2 problems on my Moto G 2014 with Android 6.0:
1. When playing in background (internal or external player) audio is interrupted (music.. few seconds of silence..music..).
2. Application stops when: Settings->Use external audio player-enable->Back->Settings->Use external audio player-disable
First problem occurs from version at leats 0.74 to 0.76. On some earlier versions it was OK.
I dont' have problem with internet connection.

**Comment by theScrabi** [comment]
Ok. I can confirm the second bug. I already fixed it.
The first bug however seems to be related to MediaPlayer. This is an issue which could be solved when we move on to exoplayer. However if so this issue is a duplicate then, since its already known.
Also please, for the future. Open two separate issues, which can be closed separately.
