### ISSUE TITLE
0.7.8 Incorrect time lenghts for videos > 1hr

### ISSUE THREAD

**Issue by ministro** [theScrabi/NewPipe#273]
Videos which last longer than 1 hour, are displayed as lasting multiple hours in the search results list.

Here? NewPipe/app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeStreamPreviewInfoExtractor.java line 61

**Comment by doodhout** [comment]
I have witnessed this very bug myself too. It seems that maybe the hour number has been replaced by the minute number or something alike.

After further inspection I think that the bug is in this file: https://github.com/theScrabi/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java

... more specifically, at the very end of the function **public static int parseDurationString(String input)**:
```
        return ((((Integer.parseInt(days) * 24)
                + Integer.parseInt(hours) * 60)
                + Integer.parseInt(minutes)) * 60)
                + Integer.parseInt(seconds);
```
There are braces missing that group the day-hours and hours together before multiplying by 60.

The solution:
```
        return (((((Integer.parseInt(days) * 24
                + Integer.parseInt(hours)) * 60)
                + Integer.parseInt(minutes)) * 60)
                + Integer.parseInt(seconds);
```

**Comment by satiricon** [comment]
Just a little mistake in the code. Fixed.
