### ISSUE TITLE
No "Copy to clipboard" option in the share menu

### ISSUE THREAD

**Issue by epitron** [theScrabi/NewPipe#31]
I'm not sure why it's happening, but the share menu doesn't have a copy to clipboard option; the only way to give someone an URL is to use the "open in browser" option. Just a heads-up. 

(I'm really liking this player BTW. I've started using it exclusively. :smile:)

**Comment by theScrabi** [comment]
Hm, i may be blind, but i never saw such an option. I'll keep it in mind.

**Comment by epitron** [comment]
Could you add a "Copy to clipboard" menu item then? Or an icon? It's a pretty important feature.

**Comment by theScrabi** [comment]
Ok.

**Comment by epitron** [comment]
Woo hoo!

**Comment by epitron** [comment]
Heh, I found another solution: https://f-droid.org/app/se.johanhil.clipboard

**Comment by theScrabi** [comment]
Can this be considered as a solution or as a workaround?

**Comment by epitron** [comment]
Just a workaround, although a surprisingly good one; it solves the copy and paste problem for every android app!

**Comment by theScrabi** [comment]
Ok if it's a workaround, I think than i still ned to implement it xD

**Comment by Rob--W** [comment]
I suggest to install a dedicated app for copying to the clipboard instead of registering an item in the share menu, because copying links is not really specific to this app, and if every app registered a copy link option, the menu would become really cluttered.

A while back I created an app specifically for this purpose. No bloat or unnecessary permissions, just a Copy link to clipboard option for URLs and for the share menu. See https://play.google.com/store/apps/details?id=nl.robwu.copylink

**Comment by theScrabi** [comment]
Right, I'd agree to that, although i'd rather prepare the free alternative to your app witch epitron posted already: https://f-droid.org/app/se.johanhil.clipboard
