### ISSUE TITLE
[Feature request] suggestions on search bar

### ISSUE THREAD

**Issue by daniell1** [theScrabi/NewPipe#5]
I'd like to request another feature: suggestions on the search bar. It would be great if the search bar provided suggestions while searching. Is that possible or would that mean using any form of Goolge API?

**Comment by theScrabi** [comment]
Sounds tricky, but since the youtube page offers suggestions in html5 it should be possible even without Google API.

**Comment by JasperWeiss** [comment]
Please allow this to be disabled in settings if implemented, that way only search strings are transmitted when pressing enter

**Comment by theScrabi** [comment]
ok

**Comment by shekhar12020** [comment]
I am working for this feature (suggestions on search bar), Please let me know if anyone has already started.

**Comment by theScrabi** [comment]
I'm not working on that feature. 

That's good, but please be careful with the architecture of newpipe. I took great care in dividing the gui, and the actual communication part. Both parts communicate though interfaces. This is done to ensure that NewPipe is able to accept other websites that youtube one day. 

In order to interfere with youtube, i'd recommend to add a function like to [SearchEngine](https://github.com/theScrabi/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/SearchEngine.java), and than instantiate it through [YoutubeSearchEngine](https://github.com/theScrabi/NewPipe/blob/master/app/src/main/java/org/schabi/newpipe/youtube/YoutubeSearchEngine.java).

**Comment by shekhar12020** [comment]
Sure, I'll take care of architecture of newpipe & also for code quality, Thanks.

**Comment by theScrabi** [comment]
Hm i should try to care about code quality myself xD.

**Comment by shekhar12020** [comment]
Hi,

I am almost done with the suggestion part but I am facing one issue with set adapter to SearchView.

**Comment by theScrabi** [comment]
Can I help with that problem?

**Comment by medavox** [comment]
Has this been finished now? Maybe we can close the ticket?

**Comment by theScrabi** [comment]
Nop so far only the backend is implemented. The UI part is not yet done.

**Comment by CHRINIMUE** [comment]
I'd think this ticket can be closed. Since Version 0.7.7 it is implemented.
